// Additional first-name -> gender classifications, layered on top of the
// original maleNames/femaleNames lists in full_report.js / month_age_area_report.js.
// Built from the 524 most frequent first names that fell through the original
// lists (each appearing 2+ times among Feb-Jul 2026 leads). Ambiguous / unisex /
// non-name tokens (titles, initials, surnames typed into the name field, short
// forms that could go either way) are deliberately left unmapped rather than guessed.
const ADDITIONS = {
  amanda: 'F', alison: 'F', diane: 'F', debbie: 'F', jennifer: 'F', cheryl: 'F',
  vicky: 'F', stacey: 'F', june: 'F', ruth: 'F', beverley: 'F', gaynor: 'F',
  vanessa: 'F', debra: 'F', shirley: 'F', jeanette: 'F', adele: 'F', carole: 'F',
  jill: 'F', anita: 'F', maxine: 'F', michaela: 'F', nichola: 'F', kathleen: 'F',
  nina: 'F', natasha: 'F', lynsey: 'F', annette: 'F', christina: 'F', valerie: 'F',
  janice: 'F', pauline: 'F', theresa: 'F', tara: 'F', lindsay: 'F', judith: 'F',
  melissa: 'F', lynda: 'F', pam: 'F', monika: 'F', carla: 'F', gina: 'F', joan: 'F',
  maggie: 'F', carolyn: 'F', howard: 'M', pamela: 'F', lyndsey: 'F', carly: 'F',
  abigail: 'F', alexandra: 'F', shaun: 'M', sharron: 'F', vicki: 'F', annie: 'F',
  janine: 'F', adrian: 'M', carrie: 'F', irene: 'F', marta: 'F', gill: 'F', lyn: 'F',
  elena: 'F', jacqui: 'F', agnieszka: 'F', sonia: 'F', sylvia: 'F', natalia: 'F',
  shelley: 'F', francesca: 'F', frances: 'F', vivienne: 'F', katrina: 'F', sonya: 'F',
  heidi: 'F', eileen: 'F', angie: 'F', colleen: 'F', faye: 'F', jen: 'F', edward: 'M',
  avril: 'F', shane: 'M', lilian: 'F', nicole: 'F', marina: 'F', cathy: 'F', matt: 'M',
  bev: 'F', loretta: 'F', kimberley: 'F', georgina: 'F', rita: 'F', sheryl: 'F',
  geraldine: 'F', monica: 'F', nancy: 'F', kathy: 'F', dianne: 'F', janette: 'F',
  martine: 'F', charlene: 'F', ewa: 'F', keri: 'F', jemma: 'F', michele: 'F',
  noreen: 'F', nataliia: 'F', shelly: 'F', samuel: 'M', allison: 'F', justine: 'F',
  marcia: 'F', caron: 'F', cherie: 'F', kristy: 'F', becky: 'F', kerrie: 'F',
  simone: 'F', alice: 'F', ingrid: 'F', norma: 'F', judit: 'F', stewart: 'M',
  ellie: 'F', serena: 'F', carolina: 'F', benjamin: 'M', erika: 'F', esther: 'F',
  will: 'M', marilyn: 'F', adriana: 'F', kristina: 'F', kenneth: 'M', catriona: 'F',
  ste: 'M', antonia: 'F', siobhan: 'F', clair: 'F', aleksandra: 'F', sylwia: 'F',
  malcolm: 'M', lena: 'F', audrey: 'F', abi: 'F', vickie: 'F', yvette: 'F', lina: 'F',
  joy: 'F', sunita: 'F', lorna: 'F', may: 'F', beata: 'F', ellen: 'F', deb: 'F',
  karolina: 'F', sadie: 'F', malgorzata: 'F', raymond: 'M', helene: 'F', bryn: 'M',
  gabrielle: 'F', belinda: 'F', chantelle: 'F', gayle: 'F', nadine: 'F', tracie: 'F',
  beverly: 'F', tricia: 'F', cath: 'F', eric: 'M', rose: 'F', katy: 'F', joseph: 'M',
  samina: 'F', russell: 'M', annmarie: 'F', sinead: 'F', nia: 'F', zara: 'F',
  lucia: 'F', henry: 'M', ursula: 'F', hanna: 'F', sophia: 'F', alexander: 'M',
  izabela: 'F', cynthia: 'F', charles: 'M', kyle: 'M', renee: 'F', brad: 'M',
  judy: 'F', lydia: 'F', dorota: 'F', shona: 'F', glen: 'M', susie: 'F', garry: 'M',
  kelvin: 'M', faisal: 'M', joann: 'F', marc: 'M', les: 'M', vikki: 'F', debs: 'F',
  rosemarie: 'F', agata: 'F', olga: 'F', jacquie: 'F', penny: 'F', ciara: 'F',
  irina: 'F', iryna: 'F', roberta: 'F', bina: 'F', tania: 'F', melinda: 'F', eve: 'F',
  tetyana: 'F', carmen: 'F', karina: 'F', clive: 'M', gwen: 'F', josie: 'F',
  louis: 'M', marlene: 'F', oksana: 'F', carlos: 'M', justin: 'M', kellie: 'F',
  lynette: 'F', erin: 'F', phyllis: 'F', ged: 'M', neville: 'M', tammy: 'F',
  kirsten: 'F', martha: 'F', candice: 'F', justyna: 'F', collette: 'F', aimee: 'F',
  sabina: 'F', daisy: 'F', martina: 'F', sabrina: 'F', lara: 'F', shazia: 'F',
  anastasia: 'F', josephine: 'F', mia: 'F', marius: 'M', shanaz: 'F', rach: 'F',
  claudia: 'F', sheena: 'F', fern: 'F', elzbieta: 'F', sherry: 'F', indre: 'F',
  abbie: 'F', penelope: 'F', daphne: 'F', bogdan: 'M', gayna: 'F', cara: 'F',
  kevan: 'M', ricardo: 'M', ronald: 'M', jez: 'M', val: 'F', francine: 'F',
  sumaiya: 'F', tamara: 'F', ricky: 'M', coral: 'F', marketa: 'F', ema: 'F',
  giles: 'M', brendan: 'M', brid: 'F', lucie: 'F', dagmara: 'F', chrissie: 'F',
  anton: 'M', cindy: 'F', bianca: 'F', kym: 'F', aggie: 'F', virginia: 'F',
  'jean-hugues': 'M', esmael: 'M', leanora: 'F', irena: 'F', hellen: 'F',
  kirsti: 'F', simona: 'F', alistair: 'M', jeannie: 'F', baiba: 'F', lucinda: 'F',
  danuta: 'F', kadie: 'F', ralph: 'M', hugh: 'M', nessa: 'F', leon: 'M',
  daniela: 'F', jermaine: 'M', spencer: 'M', mihaela: 'F', yuliya: 'F', amie: 'F',
  muhammad: 'M', kirstin: 'F', kinga: 'F', dona: 'F', davina: 'F', marianne: 'F',
  shagufta: 'F', adrianna: 'F', kavita: 'F', nadia: 'F', zarina: 'F', eleni: 'F',
  szilvia: 'F', farzana: 'F', katerina: 'F', nicholas: 'M', elisabeth: 'F',
  selina: 'F', ewelina: 'F', iveta: 'F', asma: 'F', trish: 'F', anthea: 'F',
  stacy: 'F', geoff: 'M', katalin: 'F', sabine: 'F', karl: 'M', chelle: 'F',
  leesa: 'F', lola: 'F', doreen: 'F', julian: 'M', marion: 'F', 'lee-ann': 'F',
  annemarie: 'F', tiffany: 'F', darron: 'M', vijay: 'M', 'anne-marie': 'F',
  marzena: 'F', shabana: 'F', mellissa: 'F', trudi: 'F', bindu: 'F', susana: 'F',
  adrienne: 'F', libby: 'F', dionne: 'F', solvita: 'F', danni: 'F', phillip: 'M',
  gordon: 'M', beth: 'F', christian: 'M', evelyn: 'F', mohammed: 'M', dora: 'F',
  tadeusz: 'M', steffen: 'M', ina: 'F', geoffrey: 'M', mohammad: 'M', erica: 'F',
  derrick: 'M', ivan: 'M', april: 'F', warren: 'M', gerard: 'M', lori: 'F',
  patrycja: 'F', faith: 'F', alina: 'F', layla: 'F', inga: 'F', ania: 'F',
  owen: 'M', ayesha: 'F', debi: 'F', luisa: 'F', giuseppe: 'M', alyson: 'F',
  mairead: 'F', naila: 'F', vilma: 'F', mona: 'F', violeta: 'F', kylie: 'F',
  ros: 'F', terence: 'M', enid: 'F', kev: 'M', lenny: 'M', noel: 'M', stu: 'M',
  kaye: 'F', rudy: 'M', rowena: 'F', cherrie: 'F', allan: 'M', nisha: 'F',
  rohan: 'M', philippa: 'F', tessa: 'F', rhonda: 'F', kath: 'F', bernadett: 'F',
  garba: 'M', georgiana: 'F', patsy: 'F', gabriela: 'F', vivien: 'F', bill: 'M',
  kamran: 'M', farooq: 'M', oswaldo: 'M', sonny: 'M', mariya: 'F', lekha: 'F',
  anwara: 'F', savita: 'F', dumitra: 'F', manny: 'M', raluca: 'F', lois: 'F',
  trina: 'F', aletta: 'F', mariana: 'F', philomena: 'F', leeann: 'F', tatjana: 'F',
  shabnam: 'F', kayleigh: 'F', 'toni-marie': 'F', ceri: 'F', keeley: 'F',
  shumaila: 'F', kerri: 'F', carys: 'F', mathew: 'M', uzma: 'F', lily: 'F',
  prisca: 'F', aline: 'F'
};

module.exports = ADDITIONS;
